name: CI

on:
  push:
    branches:
      - main

jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint code
        run: npm install -g eslint

      - name: Run Lint
        run: npm lint

    test:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test